#!/usr/bin/env python
"""
CIME interface to build the nemo component library
"""
import os, shutil, sys, glob

CIMEROOT = os.environ.get("CIMEROOT")
if CIMEROOT is None:
    raise SystemExit("ERROR: must set CIMEROOT environment variable")
sys.path.append(os.path.join(CIMEROOT, "scripts", "Tools"))

from standard_script_setup import *
from CIME.case import Case
from CIME.utils import expect, run_cmd
from CIME.buildlib import parse_input
from CIME.build import get_standard_makefile_args

logger = logging.getLogger(__name__)

###############################################################################
def _build_nemo():
###############################################################################

    caseroot, libroot, bldroot = parse_input(sys.argv)

    with Case(caseroot) as case:
        casetools = case.get_value("CASETOOLS")
        srcroot = case.get_value("SRCROOT")
        gmake_j = case.get_value("GMAKE_J")
        gmake = case.get_value("GMAKE")
        driver = case.get_value("COMP_INTERFACE")

        # set cpp option for nemo depending on ocean grid and passive tracer
        base_cpp = " -DCCSMCOUPLED -Dkey_diahth "

        res_cpp = " "
        drv_cpp = " "
        ver_cpp = " -Dkey_xios -Dkey_qco "
        if driver == 'nuopc':
            drv_cpp = " -DNUOPC_IN_NEMO "

        top_cpp = " "
        ocn_pstr_modules = " ".join(case.get_value("NEMO_TOP_MODULES").split())
        if ocn_pstr_modules:
            top_cpp = " -Dkey_top "
            for module in ocn_pstr_modules.split(" "):
                if module == "age":
                    top_cpp = top_cpp + " -Dkey_age "
                elif module == "cfc":
                    top_cpp = top_cpp + " -Dkey_cfc "
                else:
                    expect(False, "module %s is not a valid value in NEMO_TOP_MODULES!" %module)
    
        bfb_cpp = " "
        bfbflag = case.get_value("BFBFLAG")
        if bfbflag:
            bfb_cpp = bfb_cpp + " -Dkey_nosignedzero "
    
        dbg_cpp = " "
        dbgflag = case.get_value("DEBUG")
        if dbgflag:
            dbg_cpp = dbg_cpp + " -Dkey_nosignedzero "

        nemo_cppdefs = base_cpp + ver_cpp + res_cpp + drv_cpp + top_cpp + bfb_cpp + dbg_cpp

        # create Filepath file
        filepath_file = os.path.join(bldroot, "Filepath")
        if not os.path.isfile(filepath_file):
            paths_nemo = [os.path.join(caseroot, "SourceMods", "src.nemo"),]
            base_path = os.path.join(srcroot, "components", "nemo", "nemocore", "src", "OCE")
            paths_nemo += [x[0] for x in os.walk(base_path)]             

            paths_nemo.append(os.path.join(srcroot, "components", "nemo", "nemocore", "ext", "IOIPSL", "src"))

            if driver == 'nuopc':
                paths_nemo.append(os.path.join(srcroot, "components", "nemo", "drivers", "cpl_nuopc"))
            else:
                expect(False, "driver %s is not a valid value. " %driver)

#TODO TRACERS: TO BE UPDATED AND TESTED 
            ocn_pstr_modules = " ".join(case.get_value("NEMO_TOP_MODULES").split())
            if ocn_pstr_modules:
                base_path = os.path.join(srcroot, "components", "nemo", "nemocore", "src", "TOP")
                paths_top = [x[0] for x in os.walk(base_path)]

            with open(filepath_file, "w") as filepath:
                filepath.write("\n".join(paths_nemo))
                if ocn_pstr_modules:
                    filepath.write("\n".join(paths_top))
                filepath.write("\n")

        # build the library
        complib = os.path.join(libroot, "libocn.a")
        makefile = os.path.join(casetools, "Makefile")
        inc_xios = os.environ["XIOS_PATH"]+"/inc"
        cmd = "{} complib -j {} COMP_NAME=nemo COMPLIB={} -f {} USER_CPPDEFS=\"{}\" {} USER_INCLDIR=\"-I{}\" " \
            .format(gmake, gmake_j, complib, makefile, nemo_cppdefs, get_standard_makefile_args(case), inc_xios)

        rc, out, err = run_cmd(cmd, from_dir=bldroot)
        expect(rc == 0, "Command %s failed rc=%d\nout=%s\nerr=%s" % (cmd, rc, out, err))

        logger.info("\ncommand: \n%s \n\nbuild completed \n\noutput: \n%s \nerror: \n%s", cmd, out, err)


###############################################################################

if __name__ == "__main__":
    _build_nemo()
